<?xml version="1.0" encoding="utf-8"?><Database Name="ASS3_Q6" Class="EmpManagementClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=ASS3_Q6;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ASS3_Q6ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="dept_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dept_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Designation" Member="Designations">
    <Type Name="Designation">
      <Column Name="desg_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="desg_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Emp" Member="Emps">
    <Type Name="Emp">
      <Column Name="eno" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cv" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>